version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data
    ports:
      - '9200:9200'
volumes:
  elasticsearch_data: { }